// ============================================
// MOCK DATABASE DATA — FLYING AI LEARNING VILLA
// Contains rich, pre-populated, dynamic mock collections for local demo mode.
// ============================================

import type {
  FirestoreUser,
  FirestoreCourseProgress,
  FirestoreCertificate,
  FirestoreVideoAnalytics,
  FirestoreActivityLog,
  FirestoreNotification,
  FirestoreAttendance,
} from './firestore-types';

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();

// 1. Mock Users
export const MOCK_USERS: FirestoreUser[] = [
  {
    uid: 'u_john_smith',
    fullName: 'John Smith',
    email: 'john@villa.com',
    gender: 'Male',
    phoneNumber: '+15550199',
    dateOfBirth: '1998-05-15',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    currentDegree: 'B.Tech',
    collegeOrCompany: 'Stanford University',
    yearOfStudy: '3rd Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(10),
    lastLogin: daysAgo(0),
    avatarInitials: 'JS',
    displayName: 'John Smith',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(0),
  },
  {
    uid: 'u_alice_johnson',
    fullName: 'Alice Johnson',
    email: 'alice@villa.com',
    gender: 'Female',
    phoneNumber: '+15550244',
    dateOfBirth: '1999-09-20',
    country: 'Canada',
    state: 'Ontario',
    city: 'Toronto',
    currentDegree: 'MSc',
    collegeOrCompany: 'University of Toronto',
    yearOfStudy: '2nd Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(25),
    lastLogin: daysAgo(1),
    avatarInitials: 'AJ',
    displayName: 'Alice Johnson',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    uid: 'u_bob_patel',
    fullName: 'Bob Patel',
    email: 'bob@villa.com',
    gender: 'Male',
    phoneNumber: '+9198765432',
    dateOfBirth: '2001-12-05',
    country: 'India',
    state: 'Gujarat',
    city: 'Ahmedabad',
    currentDegree: 'BCA',
    collegeOrCompany: 'Nirma University',
    yearOfStudy: '2nd Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(8),
    lastLogin: daysAgo(0),
    avatarInitials: 'BP',
    displayName: 'Bob Patel',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(0),
  },
  {
    uid: 'u_charlie_brown',
    fullName: 'Charlie Brown',
    email: 'charlie@villa.com',
    gender: 'Male',
    phoneNumber: '+15550388',
    dateOfBirth: '1992-02-11',
    country: 'United Kingdom',
    state: 'England',
    city: 'London',
    currentDegree: 'Working Professional',
    collegeOrCompany: 'Tech Corp Ltd',
    yearOfStudy: 'N/A',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(12),
    lastLogin: daysAgo(2),
    avatarInitials: 'CB',
    displayName: 'Charlie Brown',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    uid: 'u_diana_prince',
    fullName: 'Diana Prince',
    email: 'diana@villa.com',
    gender: 'Female',
    phoneNumber: '+15550477',
    dateOfBirth: '1995-10-31',
    country: 'United States',
    state: 'New York',
    city: 'New York',
    currentDegree: 'PhD',
    collegeOrCompany: 'Columbia University',
    yearOfStudy: '1st Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(4),
    lastLogin: daysAgo(0),
    avatarInitials: 'DP',
    displayName: 'Diana Prince',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(0),
  },
  {
    uid: 'u_ethan_hunt',
    fullName: 'Ethan Hunt',
    email: 'ethan@villa.com',
    gender: 'Male',
    phoneNumber: '+15550566',
    dateOfBirth: '1994-07-07',
    country: 'Australia',
    state: 'New South Wales',
    city: 'Sydney',
    currentDegree: 'Diploma',
    collegeOrCompany: 'TAFE NSW',
    yearOfStudy: 'Final Year',
    accountStatus: 'inactive',
    role: 'student',
    registrationDate: daysAgo(30),
    lastLogin: daysAgo(15),
    avatarInitials: 'EH',
    displayName: 'Ethan Hunt',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(15),
  },
  {
    uid: 'u_fiona_gallagher',
    fullName: 'Fiona Gallagher',
    email: 'fiona@villa.com',
    gender: 'Female',
    phoneNumber: '+15550655',
    dateOfBirth: '2000-03-14',
    country: 'Ireland',
    state: 'Leinster',
    city: 'Dublin',
    currentDegree: 'BSc',
    collegeOrCompany: 'Trinity College Dublin',
    yearOfStudy: '1st Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(14),
    lastLogin: daysAgo(3),
    avatarInitials: 'FG',
    displayName: 'Fiona Gallagher',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    uid: 'u_george_clark',
    fullName: 'George Clark',
    email: 'george@villa.com',
    gender: 'Male',
    phoneNumber: '+4477009000',
    dateOfBirth: '2002-08-22',
    country: 'United Kingdom',
    state: 'Scotland',
    city: 'Edinburgh',
    currentDegree: 'Diploma',
    collegeOrCompany: 'Edinburgh College',
    yearOfStudy: '2nd Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(6),
    lastLogin: daysAgo(0),
    avatarInitials: 'GC',
    displayName: 'George Clark',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0),
  },
  {
    uid: 'u_hannah_abbott',
    fullName: 'Hannah Abbott',
    email: 'hannah@villa.com',
    gender: 'Female',
    phoneNumber: '+15550711',
    dateOfBirth: '1997-04-18',
    country: 'United States',
    state: 'Massachusetts',
    city: 'Boston',
    currentDegree: 'M.Tech',
    collegeOrCompany: 'MIT',
    yearOfStudy: '2nd Year',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(18),
    lastLogin: daysAgo(0),
    avatarInitials: 'HA',
    displayName: 'Hannah Abbott',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(0),
  },
  {
    uid: 'u_ian_malcolm',
    fullName: 'Ian Malcolm',
    email: 'ian@villa.com',
    gender: 'Male',
    phoneNumber: '+15550888',
    dateOfBirth: '1985-11-23',
    country: 'New Zealand',
    state: 'Auckland',
    city: 'Auckland',
    currentDegree: 'PhD',
    collegeOrCompany: 'University of Auckland',
    yearOfStudy: 'Graduated',
    accountStatus: 'active',
    role: 'student',
    registrationDate: daysAgo(28),
    lastLogin: daysAgo(1),
    avatarInitials: 'IM',
    displayName: 'Ian Malcolm',
    createdAt: daysAgo(28),
    updatedAt: daysAgo(1),
  },
  {
    uid: 'u_admin',
    fullName: 'Admin User',
    email: 'admin@villa.com',
    gender: 'Male',
    phoneNumber: '+15550000',
    dateOfBirth: '1990-01-01',
    country: 'United States',
    state: 'Texas',
    city: 'Austin',
    currentDegree: 'Working Professional',
    collegeOrCompany: 'Villa Academy',
    yearOfStudy: 'N/A',
    accountStatus: 'active',
    role: 'admin',
    registrationDate: daysAgo(40),
    lastLogin: daysAgo(0),
    avatarInitials: 'AU',
    displayName: 'Admin User',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(0),
  }
];

// 2. Mock Course Progress
export const MOCK_COURSE_PROGRESS: FirestoreCourseProgress[] = [
  // John Smith Progress
  { id: 'prog_john_python', userId: 'u_john_smith', courseId: 'python', started: true, startedAt: daysAgo(9), watchProgress: 75, completed: false, totalWatchTimeSeconds: 32400, lastViewedAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'prog_john_ds', userId: 'u_john_smith', courseId: 'data-science', started: true, startedAt: daysAgo(5), watchProgress: 20, completed: false, totalWatchTimeSeconds: 10800, lastViewedAt: daysAgo(2), updatedAt: daysAgo(2) },

  // Alice Johnson (Completed python & data-science)
  { id: 'prog_alice_python', userId: 'u_alice_johnson', courseId: 'python', started: true, startedAt: daysAgo(24), watchProgress: 100, completed: true, completedAt: daysAgo(20), certificateId: 'cert_alice_python', totalWatchTimeSeconds: 43200, lastViewedAt: daysAgo(20), updatedAt: daysAgo(20) },
  { id: 'prog_alice_ds', userId: 'u_alice_johnson', courseId: 'data-science', started: true, startedAt: daysAgo(19), watchProgress: 100, completed: true, completedAt: daysAgo(12), certificateId: 'cert_alice_ds', totalWatchTimeSeconds: 54000, lastViewedAt: daysAgo(12), updatedAt: daysAgo(12) },
  { id: 'prog_alice_ai', userId: 'u_alice_johnson', courseId: 'ai-ml', started: true, startedAt: daysAgo(10), watchProgress: 45, completed: false, totalWatchTimeSeconds: 32400, lastViewedAt: daysAgo(1), updatedAt: daysAgo(1) },

  // Bob Patel Progress
  { id: 'prog_bob_docker', userId: 'u_bob_patel', courseId: 'docker', started: true, startedAt: daysAgo(7), watchProgress: 90, completed: false, totalWatchTimeSeconds: 25920, lastViewedAt: daysAgo(0), updatedAt: daysAgo(0) },
  { id: 'prog_bob_mlops', userId: 'u_bob_patel', courseId: 'mlops', started: true, startedAt: daysAgo(3), watchProgress: 35, completed: false, totalWatchTimeSeconds: 17640, lastViewedAt: daysAgo(0), updatedAt: daysAgo(0) },

  // Charlie Brown Progress (Completed devops, python, hacking)
  { id: 'prog_charlie_python', userId: 'u_charlie_brown', courseId: 'python', started: true, startedAt: daysAgo(11), watchProgress: 100, completed: true, completedAt: daysAgo(8), certificateId: 'cert_charlie_python', totalWatchTimeSeconds: 43200, lastViewedAt: daysAgo(8), updatedAt: daysAgo(8) },
  { id: 'prog_charlie_devops', userId: 'u_charlie_brown', courseId: 'devops', started: true, startedAt: daysAgo(10), watchProgress: 100, completed: true, completedAt: daysAgo(6), certificateId: 'cert_charlie_devops', totalWatchTimeSeconds: 57600, lastViewedAt: daysAgo(6), updatedAt: daysAgo(6) },
  { id: 'prog_charlie_hacking', userId: 'u_charlie_brown', courseId: 'ethical-hacking', started: true, startedAt: daysAgo(5), watchProgress: 100, completed: true, completedAt: daysAgo(2), certificateId: 'cert_charlie_hacking', totalWatchTimeSeconds: 64800, lastViewedAt: daysAgo(2), updatedAt: daysAgo(2) },

  // Diana Prince Progress
  { id: 'prog_diana_ai', userId: 'u_diana_prince', courseId: 'ai-ml', started: true, startedAt: daysAgo(3), watchProgress: 60, completed: false, totalWatchTimeSeconds: 43200, lastViewedAt: daysAgo(0), updatedAt: daysAgo(0) },

  // Ethan Hunt Progress
  { id: 'prog_ethan_networking', userId: 'u_ethan_hunt', courseId: 'networking', started: true, startedAt: daysAgo(28), watchProgress: 15, completed: false, totalWatchTimeSeconds: 5400, lastViewedAt: daysAgo(15), updatedAt: daysAgo(15) },

  // Fiona Gallagher Progress
  { id: 'prog_fiona_python', userId: 'u_fiona_gallagher', courseId: 'python', started: true, startedAt: daysAgo(12), watchProgress: 30, completed: false, totalWatchTimeSeconds: 12960, lastViewedAt: daysAgo(3), updatedAt: daysAgo(3) },

  // George Clark Progress
  { id: 'prog_george_docker', userId: 'u_george_clark', courseId: 'docker', started: true, startedAt: daysAgo(5), watchProgress: 50, completed: false, totalWatchTimeSeconds: 14400, lastViewedAt: daysAgo(0), updatedAt: daysAgo(0) },

  // Hannah Abbott Progress (Completed ai-ml)
  { id: 'prog_hannah_ai', userId: 'u_hannah_abbott', courseId: 'ai-ml', started: true, startedAt: daysAgo(17), watchProgress: 100, completed: true, completedAt: daysAgo(10), certificateId: 'cert_hannah_ai', totalWatchTimeSeconds: 72000, lastViewedAt: daysAgo(10), updatedAt: daysAgo(10) },

  // Ian Malcolm Progress (Completed data-science)
  { id: 'prog_ian_ds', userId: 'u_ian_malcolm', courseId: 'data-science', started: true, startedAt: daysAgo(27), watchProgress: 100, completed: true, completedAt: daysAgo(22), certificateId: 'cert_ian_ds', totalWatchTimeSeconds: 54000, lastViewedAt: daysAgo(22), updatedAt: daysAgo(22) },
];

// 3. Mock Certificates
export const MOCK_CERTIFICATES: FirestoreCertificate[] = [
  {
    id: 'cert_alice_python',
    courseId: 'python',
    courseName: 'Python Development',
    userId: 'u_alice_johnson',
    userName: 'Alice Johnson',
    dateIssued: daysAgo(20),
    completionDate: daysAgo(20),
    formattedDate: new Date(daysAgo(20)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-PY-2026-9284',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_alice_python',
    createdAt: daysAgo(20),
  },
  {
    id: 'cert_alice_ds',
    courseId: 'data-science',
    courseName: 'Data Science & Analytics',
    userId: 'u_alice_johnson',
    userName: 'Alice Johnson',
    dateIssued: daysAgo(12),
    completionDate: daysAgo(12),
    formattedDate: new Date(daysAgo(12)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-DS-2026-1184',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_alice_ds',
    createdAt: daysAgo(12),
  },
  {
    id: 'cert_charlie_python',
    courseId: 'python',
    courseName: 'Python Development',
    userId: 'u_charlie_brown',
    userName: 'Charlie Brown',
    dateIssued: daysAgo(8),
    completionDate: daysAgo(8),
    formattedDate: new Date(daysAgo(8)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-PY-2026-4739',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_charlie_python',
    createdAt: daysAgo(8),
  },
  {
    id: 'cert_charlie_devops',
    courseId: 'devops',
    courseName: 'DevOps & Cloud Infrastructure',
    userId: 'u_charlie_brown',
    userName: 'Charlie Brown',
    dateIssued: daysAgo(6),
    completionDate: daysAgo(6),
    formattedDate: new Date(daysAgo(6)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-DO-2026-8840',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_charlie_devops',
    createdAt: daysAgo(6),
  },
  {
    id: 'cert_charlie_hacking',
    courseId: 'ethical-hacking',
    courseName: 'Ethical Hacking & Cybersecurity',
    userId: 'u_charlie_brown',
    userName: 'Charlie Brown',
    dateIssued: daysAgo(2),
    completionDate: daysAgo(2),
    formattedDate: new Date(daysAgo(2)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-EH-2026-6215',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_charlie_hacking',
    createdAt: daysAgo(2),
  },
  {
    id: 'cert_hannah_ai',
    courseId: 'ai-ml',
    courseName: 'AI & Machine Learning',
    userId: 'u_hannah_abbott',
    userName: 'Hannah Abbott',
    dateIssued: daysAgo(10),
    completionDate: daysAgo(10),
    formattedDate: new Date(daysAgo(10)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-AI-2026-0394',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_hannah_ai',
    createdAt: daysAgo(10),
  },
  {
    id: 'cert_ian_ds',
    courseId: 'data-science',
    courseName: 'Data Science & Analytics',
    userId: 'u_ian_malcolm',
    userName: 'Ian Malcolm',
    dateIssued: daysAgo(22),
    completionDate: daysAgo(22),
    formattedDate: new Date(daysAgo(22)).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    serialNumber: 'FV-DS-2026-7732',
    instructorSignature: 'Dr. Keerthana C.',
    verificationUrl: 'http://localhost:3000/verify/cert_ian_ds',
    createdAt: daysAgo(22),
  }
];

// 4. Mock Video Analytics
export const MOCK_VIDEO_ANALYTICS: FirestoreVideoAnalytics[] = [
  { id: 'v_1', videoId: 'vid_py_1', courseId: 'python', userId: 'u_john_smith', watchStartTime: daysAgo(1), watchEndTime: hoursAgo(23), totalWatchTimeSeconds: 7200, completionPercentage: 80, pausedDurationSeconds: 120, resumeCount: 3, fastForwardCount: 1, replayCount: 1, lastViewedPosition: 200, createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'v_2', videoId: 'vid_py_2', courseId: 'python', userId: 'u_john_smith', watchStartTime: daysAgo(0), watchEndTime: hoursAgo(1), totalWatchTimeSeconds: 5400, completionPercentage: 70, pausedDurationSeconds: 60, resumeCount: 2, fastForwardCount: 0, replayCount: 2, lastViewedPosition: 150, createdAt: daysAgo(0), updatedAt: daysAgo(0) },
  { id: 'v_3', videoId: 'vid_ds_1', courseId: 'data-science', userId: 'u_john_smith', watchStartTime: daysAgo(2), watchEndTime: hoursAgo(46), totalWatchTimeSeconds: 6000, completionPercentage: 50, pausedDurationSeconds: 90, resumeCount: 4, fastForwardCount: 2, replayCount: 0, lastViewedPosition: 120, createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  
  { id: 'v_4', videoId: 'vid_ai_1', courseId: 'ai-ml', userId: 'u_alice_johnson', watchStartTime: daysAgo(3), watchEndTime: hoursAgo(71), totalWatchTimeSeconds: 9000, completionPercentage: 60, pausedDurationSeconds: 400, resumeCount: 8, fastForwardCount: 4, replayCount: 1, lastViewedPosition: 400, createdAt: daysAgo(3), updatedAt: daysAgo(3) },
  { id: 'v_5', videoId: 'vid_ai_2', courseId: 'ai-ml', userId: 'u_alice_johnson', watchStartTime: daysAgo(1), watchEndTime: hoursAgo(20), totalWatchTimeSeconds: 12000, completionPercentage: 90, pausedDurationSeconds: 150, resumeCount: 5, fastForwardCount: 1, replayCount: 3, lastViewedPosition: 600, createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  
  { id: 'v_6', videoId: 'vid_doc_1', courseId: 'docker', userId: 'u_bob_patel', watchStartTime: daysAgo(4), watchEndTime: hoursAgo(95), totalWatchTimeSeconds: 8000, completionPercentage: 85, pausedDurationSeconds: 300, resumeCount: 6, fastForwardCount: 3, replayCount: 2, lastViewedPosition: 300, createdAt: daysAgo(4), updatedAt: daysAgo(4) },
  { id: 'v_7', videoId: 'vid_ml_1', courseId: 'mlops', userId: 'u_bob_patel', watchStartTime: daysAgo(0), watchEndTime: hoursAgo(2), totalWatchTimeSeconds: 10000, completionPercentage: 55, pausedDurationSeconds: 200, resumeCount: 4, fastForwardCount: 1, replayCount: 0, lastViewedPosition: 250, createdAt: daysAgo(0), updatedAt: daysAgo(0) },
  
  { id: 'v_8', videoId: 'vid_dev_1', courseId: 'devops', userId: 'u_charlie_brown', watchStartTime: daysAgo(6), watchEndTime: hoursAgo(140), totalWatchTimeSeconds: 14000, completionPercentage: 100, pausedDurationSeconds: 100, resumeCount: 3, fastForwardCount: 0, replayCount: 1, lastViewedPosition: 900, createdAt: daysAgo(6), updatedAt: daysAgo(6) },
  { id: 'v_9', videoId: 'vid_dev_2', courseId: 'devops', userId: 'u_charlie_brown', watchStartTime: daysAgo(5), watchEndTime: hoursAgo(115), totalWatchTimeSeconds: 11000, completionPercentage: 100, pausedDurationSeconds: 120, resumeCount: 4, fastForwardCount: 2, replayCount: 1, lastViewedPosition: 800, createdAt: daysAgo(5), updatedAt: daysAgo(5) },
  
  { id: 'v_10', videoId: 'vid_ai_3', courseId: 'ai-ml', userId: 'u_diana_prince', watchStartTime: daysAgo(0), watchEndTime: hoursAgo(4), totalWatchTimeSeconds: 18000, completionPercentage: 70, pausedDurationSeconds: 50, resumeCount: 1, fastForwardCount: 0, replayCount: 0, lastViewedPosition: 700, createdAt: daysAgo(0), updatedAt: daysAgo(0) },
  { id: 'v_11', videoId: 'vid_ai_4', courseId: 'ai-ml', userId: 'u_diana_prince', watchStartTime: daysAgo(2), watchEndTime: hoursAgo(44), totalWatchTimeSeconds: 12000, completionPercentage: 50, pausedDurationSeconds: 110, resumeCount: 2, fastForwardCount: 1, replayCount: 1, lastViewedPosition: 500, createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  
  { id: 'v_12', videoId: 'vid_py_3', courseId: 'python', userId: 'u_charlie_brown', watchStartTime: daysAgo(10), watchEndTime: hoursAgo(230), totalWatchTimeSeconds: 15000, completionPercentage: 100, pausedDurationSeconds: 80, resumeCount: 2, fastForwardCount: 1, replayCount: 2, lastViewedPosition: 1000, createdAt: daysAgo(10), updatedAt: daysAgo(10) },
  { id: 'v_13', videoId: 'vid_hack_1', courseId: 'ethical-hacking', userId: 'u_charlie_brown', watchStartTime: daysAgo(7), watchEndTime: hoursAgo(160), totalWatchTimeSeconds: 22000, completionPercentage: 100, pausedDurationSeconds: 300, resumeCount: 9, fastForwardCount: 5, replayCount: 4, lastViewedPosition: 1200, createdAt: daysAgo(7), updatedAt: daysAgo(7) },

  { id: 'v_14', videoId: 'vid_ai_5', courseId: 'ai-ml', userId: 'u_hannah_abbott', watchStartTime: daysAgo(12), watchEndTime: hoursAgo(280), totalWatchTimeSeconds: 28000, completionPercentage: 100, pausedDurationSeconds: 250, resumeCount: 5, fastForwardCount: 2, replayCount: 2, lastViewedPosition: 1500, createdAt: daysAgo(12), updatedAt: daysAgo(12) },
  { id: 'v_15', videoId: 'vid_ds_2', courseId: 'data-science', userId: 'u_ian_malcolm', watchStartTime: daysAgo(24), watchEndTime: hoursAgo(570), totalWatchTimeSeconds: 25000, completionPercentage: 100, pausedDurationSeconds: 180, resumeCount: 3, fastForwardCount: 0, replayCount: 1, lastViewedPosition: 1200, createdAt: daysAgo(24), updatedAt: daysAgo(24) },
];

// 5. Mock Notifications
export const MOCK_NOTIFICATIONS: FirestoreNotification[] = [
  { id: 'notif_1', type: 'new_registration', title: 'New Registration', message: 'Bob Patel registered for the academy.', userId: 'u_bob_patel', userName: 'Bob Patel', read: false, createdAt: daysAgo(1) },
  { id: 'notif_2', type: 'course_completion', title: 'Course Completed', message: 'Charlie Brown completed Ethical Hacking.', userId: 'u_charlie_brown', userName: 'Charlie Brown', courseId: 'ethical-hacking', courseName: 'Ethical Hacking', read: false, createdAt: daysAgo(2) },
  { id: 'notif_3', type: 'certificate_generated', title: 'Certificate Issued', message: 'Certificate issued to Charlie Brown for Ethical Hacking.', userId: 'u_charlie_brown', userName: 'Charlie Brown', read: true, createdAt: daysAgo(2) },
  { id: 'notif_4', type: 'inactive_student', title: 'Inactive Student Alert', message: 'Ethan Hunt has not logged in for 15 days.', userId: 'u_ethan_hunt', userName: 'Ethan Hunt', read: false, createdAt: daysAgo(3) },
  { id: 'notif_5', type: 'new_registration', title: 'New Registration', message: 'Diana Prince registered for the academy.', userId: 'u_diana_prince', userName: 'Diana Prince', read: true, createdAt: daysAgo(4) },
  { id: 'notif_6', type: 'low_activity', title: 'Low Learning Pace', message: 'Fiona Gallagher watched less than 1 hour this week.', userId: 'u_fiona_gallagher', userName: 'Fiona Gallagher', read: false, createdAt: daysAgo(5) },
  { id: 'notif_7', type: 'new_registration', title: 'New Registration', message: 'George Clark registered for the academy.', userId: 'u_george_clark', userName: 'George Clark', read: true, createdAt: daysAgo(6) },
  { id: 'notif_8', type: 'course_completion', title: 'Course Completed', message: 'Hannah Abbott completed AI & Machine Learning.', userId: 'u_hannah_abbott', userName: 'Hannah Abbott', courseId: 'ai-ml', courseName: 'AI & Machine Learning', read: true, createdAt: daysAgo(10) },
];

// 6. Mock Activity Logs
export const MOCK_ACTIVITY_LOGS: FirestoreActivityLog[] = [
  { id: 'act_1', userId: 'u_john_smith', userName: 'John Smith', type: 'logged_in', description: 'John Smith logged into the Learning Villa.', createdAt: hoursAgo(1) },
  { id: 'act_2', userId: 'u_john_smith', userName: 'John Smith', type: 'watched_video', description: 'Watched 45 mins of Python development.', courseId: 'python', courseName: 'Python Development', createdAt: hoursAgo(2) },
  { id: 'act_3', userId: 'u_bob_patel', userName: 'Bob Patel', type: 'watched_video', description: 'Watched 20 mins of MLOps container builds.', courseId: 'mlops', courseName: 'MLOps Engineering', createdAt: hoursAgo(4) },
  { id: 'act_4', userId: 'u_diana_prince', userName: 'Diana Prince', type: 'watched_video', description: 'Started Neural Network models.', courseId: 'ai-ml', courseName: 'AI & Machine Learning', createdAt: hoursAgo(6) },
  { id: 'act_5', userId: 'u_george_clark', userName: 'George Clark', type: 'logged_in', description: 'George Clark logged into the Learning Villa.', createdAt: hoursAgo(10) },
  { id: 'act_6', userId: 'u_bob_patel', userName: 'Bob Patel', type: 'registered', description: 'Bob Patel created an academy account.', createdAt: daysAgo(1) },
  { id: 'act_7', userId: 'u_charlie_brown', userName: 'Charlie Brown', type: 'downloaded_certificate', description: 'Downloaded Ethical Hacking certificate.', createdAt: daysAgo(2) },
  { id: 'act_8', userId: 'u_charlie_brown', userName: 'Charlie Brown', type: 'completed_course', description: 'Completed Ethical Hacking room successfully.', courseId: 'ethical-hacking', courseName: 'Ethical Hacking', createdAt: daysAgo(2) },
  { id: 'act_9', userId: 'u_alice_johnson', userName: 'Alice Johnson', type: 'logged_in', description: 'Alice Johnson logged into the Learning Villa.', createdAt: daysAgo(2) },
  { id: 'act_10', userId: 'u_john_smith', userName: 'John Smith', type: 'enrolled', description: 'Enrolled in Data Science course.', courseId: 'data-science', courseName: 'Data Science & Analytics', createdAt: daysAgo(5) },
  { id: 'act_11', userId: 'u_hannah_abbott', userName: 'Hannah Abbott', type: 'completed_course', description: 'Completed AI & Machine Learning room successfully.', courseId: 'ai-ml', courseName: 'AI & Machine Learning', createdAt: daysAgo(10) },
  { id: 'act_12', userId: 'u_alice_johnson', userName: 'Alice Johnson', type: 'completed_course', description: 'Completed Data Science room successfully.', courseId: 'data-science', courseName: 'Data Science & Analytics', createdAt: daysAgo(12) },
  { id: 'act_13', userId: 'u_ian_malcolm', userName: 'Ian Malcolm', type: 'completed_course', description: 'Completed Data Science room successfully.', courseId: 'data-science', courseName: 'Data Science & Analytics', createdAt: daysAgo(22) },
];

// 7. Mock Attendance
export const MOCK_ATTENDANCE: FirestoreAttendance[] = [
  { id: 'att_1', userId: 'u_john_smith', loginTime: hoursAgo(1), sessionDurationMinutes: 45, ipAddress: '192.168.1.5', userAgent: 'Chrome Windows', createdAt: hoursAgo(1) },
  { id: 'att_2', userId: 'u_john_smith', loginTime: daysAgo(1), sessionDurationMinutes: 120, ipAddress: '192.168.1.5', userAgent: 'Chrome Windows', createdAt: daysAgo(1) },
  { id: 'att_3', userId: 'u_john_smith', loginTime: daysAgo(2), sessionDurationMinutes: 60, ipAddress: '192.168.1.5', userAgent: 'Chrome Windows', createdAt: daysAgo(2) },
  
  { id: 'att_4', userId: 'u_alice_johnson', loginTime: daysAgo(1), sessionDurationMinutes: 180, ipAddress: '192.168.2.12', userAgent: 'Safari macOS', createdAt: daysAgo(1) },
  { id: 'att_5', userId: 'u_alice_johnson', loginTime: daysAgo(3), sessionDurationMinutes: 110, ipAddress: '192.168.2.12', userAgent: 'Safari macOS', createdAt: daysAgo(3) },
  { id: 'att_6', userId: 'u_alice_johnson', loginTime: daysAgo(10), sessionDurationMinutes: 200, ipAddress: '192.168.2.12', userAgent: 'Safari macOS', createdAt: daysAgo(10) },

  { id: 'att_7', userId: 'u_bob_patel', loginTime: daysAgo(0), sessionDurationMinutes: 90, ipAddress: '103.24.55.8', userAgent: 'Firefox Linux', createdAt: daysAgo(0) },
  { id: 'att_8', userId: 'u_bob_patel', loginTime: daysAgo(1), sessionDurationMinutes: 75, ipAddress: '103.24.55.8', userAgent: 'Firefox Linux', createdAt: daysAgo(1) },

  { id: 'att_9', userId: 'u_charlie_brown', loginTime: daysAgo(2), sessionDurationMinutes: 240, ipAddress: '88.42.112.5', userAgent: 'Chrome macOS', createdAt: daysAgo(2) },
  { id: 'att_10', userId: 'u_charlie_brown', loginTime: daysAgo(5), sessionDurationMinutes: 130, ipAddress: '88.42.112.5', userAgent: 'Chrome macOS', createdAt: daysAgo(5) },
  
  { id: 'att_11', userId: 'u_diana_prince', loginTime: daysAgo(0), sessionDurationMinutes: 300, ipAddress: '172.56.21.9', userAgent: 'Chrome Windows', createdAt: daysAgo(0) },
  { id: 'att_12', userId: 'u_diana_prince', loginTime: daysAgo(2), sessionDurationMinutes: 150, ipAddress: '172.56.21.9', userAgent: 'Chrome Windows', createdAt: daysAgo(2) },
  
  { id: 'att_13', userId: 'u_hannah_abbott', loginTime: daysAgo(0), sessionDurationMinutes: 40, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(0) },
  { id: 'att_14', userId: 'u_hannah_abbott', loginTime: daysAgo(1), sessionDurationMinutes: 90, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(1) },
  { id: 'att_15', userId: 'u_hannah_abbott', loginTime: daysAgo(2), sessionDurationMinutes: 80, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(2) },
  { id: 'att_16', userId: 'u_hannah_abbott', loginTime: daysAgo(3), sessionDurationMinutes: 120, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(3) },
  { id: 'att_17', userId: 'u_hannah_abbott', loginTime: daysAgo(4), sessionDurationMinutes: 100, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(4) },
  { id: 'att_18', userId: 'u_hannah_abbott', loginTime: daysAgo(5), sessionDurationMinutes: 60, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(5) },
  { id: 'att_19', userId: 'u_hannah_abbott', loginTime: daysAgo(6), sessionDurationMinutes: 110, ipAddress: '18.2.55.109', userAgent: 'Edge Windows', createdAt: daysAgo(6) },
];
